pool: Agentpool1

trigger: none

stages:
  - stage: initandPlan
    displayName: initandPlan
    jobs:
    - job: initandPlan
      displayName: initandPlan
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        displayName: "initandPlan"
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          backendServiceArm: 'Service Connection firsttwo'
          backendAzureRmResourceGroupName: 'rgchikni'
          backendAzureRmStorageAccountName: 'stbackend12'
          backendAzureRmContainerName: 'container12'
          backendAzureRmKey: 'dev.terraform.tfstate'
      - task: TerraformTaskV4@4
        displayName: "plan"
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          environmentServiceNameAzureRM: 'Service Connection firsttwo' 
  - stage: apply
    displayName: apply
    jobs:
    - job: manualvalidationjob 
      #timeoutInMinutes: 90
      displayName: manualvalidationjob
      pool: server
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'kuberdev66666@gmail.com'
          approvers: 'kuberdev66666@gmail.com'
          instructions: 'pls approve'
    - job: apply
      dependsOn: manualvalidationjob
      displayName: apply  
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        displayName: "initandPlan"
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          backendServiceArm: 'Service Connection firsttwo'
          backendAzureRmResourceGroupName: 'rgchikni'
          backendAzureRmStorageAccountName: 'stbackend12'
          backendAzureRmContainerName: 'container12'
          backendAzureRmKey: 'dev.terraform.tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
          environmentServiceNameAzureRM: 'Service Connection firsttwo' 
